#!/bin/bash
#
# This script will build Xchecklist for lin, win and mac for XP 10 and 11 using Cmake
#
# How to run
# cd $Xchecklist_REPO
# ./buildXchecklist_all_64bit_OnLinux_WithCmake

rm -r Xchecklist/*
mkdir -p Xchecklist/64 &&
mkdir -p Xchecklist/Checker &&
mkdir -p Xchecklist/Documentation &&


# Windows build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-mingw-w64-x86-64.cmake
cmake --build ./build
cp ./build/win.xpl ./Xchecklist/64/


rm -r build/*
cmake -S ./checker -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-mingw-w64-x86-64.cmake
cmake --build ./build
cp ./build/win_checker_64bit.exe ./Xchecklist/Checker/



# Linux build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build
cp ./build/lin.xpl ./Xchecklist/64/


rm -r build/*
cmake -S ./checker -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build
cp ./build/lin_checker_64 ./Xchecklist/Checker/


rm -r build/*
cmake -S ./simon -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build
cp ./build/simon_lin64 ./Xchecklist/



# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-ubuntu-osxcross-11.3-x86_64.cmake
cmake --build ./build
cp ./build/mac.xpl ./Xchecklist/64/


rm -r build/*
cmake -S ./checker -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-ubuntu-osxcross-11.3-x86_64.cmake
cmake --build ./build
cp ./build/mac_checker ./Xchecklist/Checker/


rm -r build/*
cmake -S ./simon -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-ubuntu-osxcross-11.3-x86_64.cmake
cmake --build ./build
cp ./build/simon_mac ./Xchecklist/


# Docs copy
cp docs/XchecklistUserManual.pdf Xchecklist/Documentation
cp ChangeLog.txt Xchecklist/Documentation
cp checker/clist.txt Xchecklist/Checker
# cp checker/regres_test1.txt Xchecklist/Checker
