#!/bin/bash
#
# This script will build Xchecklist for lin, win and mac for XP 11, 19 and 9 using Cmake
#
# How to run
# ./xp11_xchecklist_plugin_builder/xchecklist/buildXchecklist_lin_win_mac_OnLinux_WithCmake

cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist

make distclean >/dev/null
rm -rf release
mkdir -p release/Checker &&
mkdir -p release/Xchecklist/64 &&
mkdir -p release/Xchecklist/lin_x64 &&
mkdir -p release/Xchecklist/win_x64 &&
mkdir -p release/Xchecklist/mac_x64

# Building for X-Plane 11

cd src
mkdir -p build
rm -r build/*
cd build
cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp src/build/Xchecklist.xpl release/Xchecklist/lin_x64/
cp src/build/Xchecklist.xpl release/Xchecklist/64/lin.xpl
cp src/build/Xchecklist.xpl release/Xchecklist/lin.xpl

cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-mingw-w64-x86-64.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp src/build/Xchecklist.xpl release/Xchecklist/win_x64/
cp src/build/Xchecklist.xpl release/Xchecklist/64/win.xpl
cp src/build/Xchecklist.xpl release/Xchecklist/win.xpl

cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-ubuntu-osxcross-10.11.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp src/build/Xchecklist.xpl release/Xchecklist/mac_x64/
cp src/build/Xchecklist.xpl release/Xchecklist/64/mac.xpl
cp src/build/Xchecklist.xpl release/Xchecklist/mac.xpl


# Building Checker
cd checker
mkdir -p build
rm -r build/*
cd build
cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp checker/build/lin_checker_64 release/Checker/

cd checker
mkdir -p build
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-mingw-w64-x86-64.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp checker/build/win_checker_64bit.exe release/Checker/

cd checker
mkdir -p build
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-ubuntu-osxcross-10.11.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp checker/build/mac_checker release/Checker/

exec $SHELL
#
