#!/bin/bash
#
# This script will build Xchecklist for lin, win and mac for XP 11, 19 and 9 using Cmake
#
# How to run
# ./buildXchecklist_all_OnLinux_WithCmake

rm -rf release build
mkdir -p release/Checker &&
mkdir -p release/Xchecklist/64 &&
mkdir build

##########################################################################
# Building Linux 32bit
rm -r build/*
pushd build
cmake -D32BIT=ON ../src &&
make VERBOSE=1 &&
cp liblin.xpl ../release/Xchecklist/lin.xpl
popd
rm -r build/*
pushd build
cmake -D32BIT=ON ../checker &&
make VERBOSE=1 &&
cp lin_checker_32 ../release/Checker
popd
rm -r build/*
pushd build
cmake -D32BIT=ON ../simon &&
make VERBOSE=1 &&
cp simon_lin32 ../release/Xchecklist
popd

# Building Linux 64bit
rm -r build/*
pushd build
cmake ../src &&
make VERBOSE=1 &&
cp liblin.xpl ../release/Xchecklist/64/lin.xpl
popd
rm -r build/*
pushd build
cmake ../checker &&
make VERBOSE=1 &&
cp lin_checker_64 ../release/Checker
popd
rm -r build/*
pushd build
cmake ../simon &&
make VERBOSE=1 &&
cp simon_lin64 ../release/Xchecklist
popd

# Building Windows 64bit
rm -r build/*
pushd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake ../src &&
make VERBOSE=1 &&
cp libwin.xpl ../release/Xchecklist/64/win.xpl
popd
rm -r build/*
pushd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake ../checker &&
make VERBOSE=1 &&
cp win_checker_64bit.exe ../release/Checker
popd


# Building Windows 32bit
rm -r build/*
pushd build
cmake -D32BIT=ON -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-i686.cmake ../src &&
make VERBOSE=1 &&
cp libwin.xpl ../release/Xchecklist/win.xpl
popd
rm -r build/*
pushd build
cmake -D32BIT=ON -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-i686.cmake ../checker &&
make VERBOSE=1 &&
cp win_checker_32bit.exe ../release/Checker
popd

# Building Mac
rm -r build/*
pushd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-10.11.cmake ../src &&
make VERBOSE=1 &&
cp libmac.xpl ../release/Xchecklist/mac.xpl
popd
rm -r build/*
pushd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-10.11.cmake ../checker &&
make VERBOSE=1 &&
cp mac_checker ../release/Checker
popd
rm -r build/*
pushd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-10.11.cmake ../simon &&
make VERBOSE=1 &&
cp simon_mac ../release/Xchecklist
popd

exec $SHELL
#
