#!/bin/bash
#
cd X-Plane_Github_Plugins/xchecklist &&
./build4linux &&

ssh -v Bills-Mac-Pro-Yos.local ". ~/.bash_profile && cd X-Plane_Github_Plugins/xchecklist && git pull && ./build4mac"
exec $SHELL
#

