#!/bin/bash
#
make distclean >/dev/null
rm -rf lipo_temp
rm -rf release
mkdir -p lipo_temp &&
mkdir -p release/Checker &&
mkdir -p release/Xchecklist/64 &&
mkdir -p release/Xchecklist/mac_x64 &&
make distclean >/dev/null
qmake -spec /Volumes/YosemiteHome/bill/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang-32 Xchecklist.pro && make &&
cp plugin/libmac.xpl.dylib lipo_temp/mac32.xpl &&
cp checker/checker lipo_temp/mac_checker_32bit &&
cp simon/simon_mac lipo_temp/simon_mac32
if [ $? != 0 ] ; then
  exit
fi


make distclean >/dev/null
qmake -spec /Volumes/YosemiteHome/bill/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang Xchecklist.pro && make &&
cp plugin/libmac.xpl.dylib lipo_temp/mac64.xpl &&
cp checker/checker lipo_temp/mac_checker_64bit &&
cp simon/simon_mac lipo_temp/simon_mac64
if [ $? != 0 ] ; then
  exit
fi


make distclean >/dev/null
qmake -spec /Volumes/YosemiteHome/bill/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang Xchecklist_mac_x64.pro && make &&
cp plugin_mac_x64/libmac.xpl.dylib release/Xchecklist/mac_x64/Xchecklist.xpl
if [ $? != 0 ] ; then
  exit
fi

make distclean >/dev/null

lipo -create lipo_temp/mac_checker_32bit lipo_temp/mac_checker_64bit -output release/Checker/mac_checker

lipo -create lipo_temp/mac32.xpl lipo_temp/mac64.xpl -output release/Xchecklist/mac.xpl

lipo -create lipo_temp/simon_mac32 lipo_temp/simon_mac64 -output release/Xchecklist/simon_mac

./copy_Xchecklist

#

