#!/bin/bash
#
# How to run
# ./xp11_xchecklist_plugin_builder/xchecklist/buildGithubXchecklistOnLinux_cmake

cd xp11_xchecklist_plugin_builder/xchecklist &&
# ./build4linux_cmake
./build4_lin_win_mac_cmake

# ./build4linux
# ./MakeMacOnLinux
# ssh -v Bills-Mac-Pro-Yos.local ". ~/.bash_profile && cd X-Plane_Github_Plugins/xchecklist && git pull && ./build4mac"
exec $SHELL
#
ls
