#!/bin/bash
#
make distclean >/dev/null
rm -rf release
mkdir -p release/Checker &&
mkdir -p release/Xchecklist/64 &&
mkdir -p release/Xchecklist/lin_x64 &&
mkdir -p release/Xchecklist/win_x64 &&
mkdir -p release/Xchecklist/mac_x64


cd src
rm -r build/*
cd build
cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp src/build/Xchecklist.xpl release/Xchecklist/lin_x64/


cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-mingw-w64-x86-64.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp src/build/Xchecklist.xpl release/Xchecklist/win_x64/


cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xchecklist_plugin_builder/xchecklist/src/Toolchain-ubuntu-osxcross-10.11.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist
cp src/build/Xchecklist.xpl release/Xchecklist/mac_x64/

#

