#!/bin/bash
#
make distclean >/dev/null
rm -rf release
mkdir -p release/Checker &&
mkdir -p release/Xchecklist/64 &&
mkdir -p release/Xchecklist/lin_x64 &&
mkdir -p release/Xchecklist/win_x64 &&
mkdir -p release/Xchecklist/mac_x64

./make_flex_and_bison

cd src && rm -r build/* && cd build &&
cmake .. && make VERBOSE=1 &&
cd /home/bill/xp11_xchecklist_plugin_builder/xchecklist

#

