#!/bin/bash
#

scp release/Checker/mac_checker bill@billsim-64-1404.local:X-Plane_Github_Plugins/xchecklist/release/Checker/mac_checker

scp release/Xchecklist/mac.xpl bill@billsim-64-1404.local:X-Plane_Github_Plugins/xchecklist/release/Xchecklist/mac.xpl

scp release/Xchecklist/simon_mac bill@billsim-64-1404.local:X-Plane_Github_Plugins/xchecklist/release/Xchecklist/simon_mac

scp release/Xchecklist/mac_x64/Xchecklist.xpl bill@billsim-64-1604.local:X-Plane_Github_Plugins/xchecklist/release/Xchecklist/mac_x64/Xchecklist.xpl


#

